# Setup
title:              Usman Khan 
#tagline:             'The man, the myth, the [undead] legend...'
description:         'I wanted to make a website to use as a journal, basically. So here it is.'
url:                 'https://kodiak.beardom.xyz'
siteurl:             'https://kodiak.beardom.xyz'
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Usman Khan 
  #  url:               https://kodiak.beardom.xyz
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
